# Generated by Django 5.1.3 on 2024-11-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.TextField(blank=True, help_text='Comma-separated list of colors', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_colors',
            field=models.BooleanField(default=False),
        ),
    ]
